### ISSUE TITLE
Delete a message/process in a queue

### ISSUE THREAD

**Issue by BahramAskari** [weyoss/redis-smq#108]
Hello
I have a queue which am producing messages into it; But usually is possible for me to send a message to that queue, whether a same one is processing or not. I want to delete the same previous message (I have its id) even if is processing (cancelling that process and do the other messages).
I had tried to use the below method; But nothing is happened.

```js
const msgId = "124320i46958490wu52e";
const Msg = new Message()

Msg.getMessageState(msgId, (err, resp)=> {
    if (!err) state=resp
    // this works and returns the message
})

Msg.deleteMessageById(msgId, (err)=> {
                    if (err) {
                     // no error has been logged
                    } else {
                   // reached, but message did not deleted. I want to cancel and delete the process by messageId from the queue to do process on the newer same message
                    }
                })
```

**Comment by weyoss** [comment]
@BahramAskari Thank you for opening this issue.

Please **indicate which redis-smq release** are you using and **provide the full steps needed to reproduce your issue**. So we can discuss it. 

Additionally, you should not use `getMessageState()` method to retrieve the message from the MQ. `deleteMessageById()` returns an error only if the message does not exist. Otherwise it gracefully tries to delete it. Messages that can not be deleted are simply skipped.
