### ISSUE TITLE
Issue with consumer

### ISSUE THREAD

**Issue by zazoomauro** [weyoss/redis-smq#25]
My consumer class looks like: 

(tried with with and without the constructor method. Same issue)

```js
import {Consumer} from 'redis-smq';

/**
 * Consumer manager
 */
export default class ConsumerQueueManager extends Consumer {
  constructor() {
    super();
  }

  /**
   * @param {Message} message
   * @param {function} cb
   */
  consume(message, cb) {
    console.debug(message);
    cb();
  }
}
```

my application kernel (who starts the consumer)
```js
/**
   * Run consumer payment process
   */
  async runConsumerQueueProcess() {
    if (!process.argv.includes('--process-consumer-queue-disabled')) {
      this._logger.info('Starting consumer queue process');
      ConsumerQueueManager.queueName = config.queue.name;
      const consumerManager = new ConsumerQueueManager();
      consumerManager.run();
    }
  }
```

got this error:
```
error: [general] TypeError: Class constructor Consumer cannot be invoked without 'new'
```

**Comment by weyoss** [comment]
Please provide more information about your environment. Are you using babel or running nodejs with `--experimental-modules` flag?

It  seems that you are having a problem with ES6 modules and commonjs which is used by this packages (module.exports/require). This issue seems not to be related with the package itself.

I believe that mixing ES6 modules with commonjs does not work and it should be avoided.

Have you tried to use module.exports/require instead of import/export? 

I mean this way:

```javascript
const { Consumer } = require('redis-smq');

/**
 * Consumer manager
 */
module.exports = class ConsumerQueueManager extends Consumer {
  constructor() {
    super();
  }

  /**
   * @param {Message} message
   * @param {function} cb
   */
  consume(message, cb) {
    console.debug(message);
    cb();
  }
}
```

Then in you application kernel import ConsumerQueueManager like:
```javascript
const ConsumerQueueManager = require('./consumer-path');
...
```

**Comment by zazoomauro** [comment]
I already tried and same problem.
I´m using babel to transpile the project and I´m trying babel-watch to develop locally

**Comment by zazoomauro** [comment]
* I´m using node v10.3.0
*

**Comment by weyoss** [comment]
I  am convinced that this issue is related to babel and the way it transpiles the code.

Unfortunately I do not provide any assistance with babel issues as they are not related to this project.

I suggest you inspect the transpiled code. Google can be your best friend.

https://www.google.com/search?q=ES6%2FBabel+Class+constructor+cannot+be+invoked+without+%27new%27&oq=ES6%2FBabel+Class+constructor+cannot+be+invoked+without+%27new

**Comment by weyoss** [comment]
This package has been tested on node v10.3.0 and all tests passed successfully.

**Comment by zazoomauro** [comment]
@weyoss You were totally right. If somebody is using babel needs to exclude class transform:

```json
"presets": [
      ["@babel/preset-env", { "exclude": ["transform-classes"] }]
    ],
```

**Comment by weyoss** [comment]
Glad you got it fixed!
