### ISSUE TITLE
Retain messages in queue (TTL)

### ISSUE THREAD

**Issue by s888** [weyoss/redis-smq#37]
Hi,

After researching for all the available Redis queues, I found this to be the best for our use case :)

Since I haven't encountered any errors yet and it fulfills most of the use case.

I just wanted to clarify a few things, Let me know if this is not possible.
-I have multiple workers that process jobs, no 2 workers should process the same job.
-After a worker's job is complete the worker ACKs the job ( using cb() ). Until then the job is unavailable for other workers.
-If one of the apps terminates abruptly; e.g. via CTRL-C then the job should be sent back to the queue so that it can be picked by the next available worker. Which I think it does.
(correct me if it will not since that is the most important criteria)

However, I do not want to remove the message automatically from the queue. Messages should only be removed by the worker. 
I tried doing this ```message.setBody(msg).setTTL(-1) ``` but it gives error.

Is there a way to do so. If not what is the maximum TTL that I can provide.

**Comment by weyoss** [comment]
Hi,

> -If one of the apps terminates abruptly; e.g. via CTRL-C then the job should be sent back to the queue so that it can be picked by the next available worker. Which I think it does.
(correct me if it will not since that is the most important criteria)

Correct.

> However, I do not want to remove the message automatically from the queue. Messages should only be removed by the worker.

By design, garbage collector instance is responsible for collecting, re-queuing or destroying messages from crashed consumers. It is not the consumer responsibility. Further more the consumer instance is statefull-less (each time a consumer is started, it got a new ID, and a new processing queue). Consumers can only acknowledge/unack. a message.

> I tried doing this message.setBody(msg).setTTL(-1) but it gives error.
Is there a way to do so. If not what is the maximum TTL that I can provide.

You are wrongly using setTTL method. From the docs here: https://github.com/weyoss/redis-smq/blob/master/docs/api/message.md#messageprototypesetttl, the TTL message property is intented only for expiring a given message after a certain amount (a positive number) of time. If you want a message to stay forever in the message queue until it is delivered to a consumer then you should not set TTL. The maximum TTL value is Number.MAX_SAFE_INTEGER (2^53 - 1).
