### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by raijinsetsu** [weyoss/redis-smq#41]
It's not explicitly stated but the library appears to rely on Redis being configured for persistence. In other words: there is no way for us to provide our own persistence mechanism.

Our product is deployed to a large number of customers with Redis persistence disabled. I would LOVE to be able to just switch Redis persistence on, but updating deployments is... complicated and likely to break installations. I have reached out to other contributors and management for input on making this switch but, in the mean time, I'm looking at alternatives.

Would a PR that allows us to provide a "Persistence" class be accepted? The assumption is that the default class's functionality would always be a no-op and rely on Redis. In our case, we could provide an instance of this class through the configuration and the library would call the functions on that instance to persistence the data else-where.

**Comment by weyoss** [comment]
> It's not explicitly stated but the library appears to rely on Redis being configured for persistence. In other words: there is no way for us to provide our own persistence mechanism.

First of all, the name of the MQ is RedisMQ, meaning at least that it is has a dependency on Redis for providing its keys features. 

The dependency on Redis is  EXPLICITLY stated in the docs. See [Installation](https://github.com/weyoss/redis-smq#installation). It says:
 
> Minimal Redis server version is 2.6.12 

Apart from that, the docs also suggest to take a look at the [MQ design and concepts](https://medium.com/@weyoss/building-a-simple-message-queue-using-redis-server-and-node-js-964eda240a2a) page, to understand how this MQ works. The design page says:

> The basis of RedisSMQ is the Redis itself which already provides atomic operations and can be configured to be highly available. Also Redis can be tuned to match exactly our requirements when dealing with persistence vs performance.

Finally, regarding your last question:

> Would a PR that allows us to provide a "Persistence" class be accepted?   

I believe that it's not the way to go, because the basis of this MQ is Redis and you can not swap it for another persistence. The Redis is not only a persistence layer for the MQ, but more than that. Once again, take a look at the design page. If you do swap Redis for another persistence, let's say MongoDB, then you would need to rewrite the whole MQ leading to a completely new MQ.

**Comment by weyoss** [comment]
So unfortunately your PR would not be accepted.
